"""Remove Kvasir-SEG near-duplicates from the HyperKvasir pretraining corpus.

This is a thesis-defence item, not housekeeping.

Kvasir-SEG's 1000 images come from the same colonoscopy procedures that HyperKvasir was
assembled from. Exact file overlap is not guaranteed by construction — our corpus is the
*unlabeled* split — but near-duplicate frames of the same polyp almost certainly are
present. If one of those sits in pretraining and its twin is in the segmentation test
set, the reported Dice is partly measuring memorisation, and that is the single most
damaging objection this work can face.

So: perceptual-hash all 1000 Kvasir-SEG images against all ~99,417 pretraining images,
write every match to `splits/pretrain_excluded.txt`, and report the count in the thesis.
`HyperKvasirUnlabeled` reads that file and drops those images.

Runs on a Kaggle CPU session — free, no GPU quota.

    python scripts/dedup_phash.py --threshold 6
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

import numpy as np
from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from src.config import IMAGE_EXTS, REPO_ROOT, resolve_dataset_dir  # noqa: E402
from src.data.kvasir_seg import find_image_and_mask_dirs  # noqa: E402
from src.data.splits import phash  # noqa: E402

try:
    from PIL import ImageFile

    ImageFile.LOAD_TRUNCATED_IMAGES = True
except ImportError:
    pass


def hash_dir(paths: list[Path], label: str) -> tuple[np.ndarray, list[Path]]:
    """Hash a list of images, returning a uint64 array and the paths that succeeded."""
    hashes, kept = [], []
    t0 = time.time()
    for i, p in enumerate(paths):
        if i and i % 5000 == 0:
            rate = i / max(1e-6, time.time() - t0)
            print(f"[dedup] {label}: {i}/{len(paths)}  {rate:.0f} img/s  "
                  f"ETA {(len(paths) - i) / max(1e-6, rate) / 60:.1f} min")
        try:
            hashes.append(phash(Image.open(p)))
            kept.append(p)
        except Exception as e:  # noqa: BLE001
            print(f"[dedup] skipping unreadable {p.name}: {e}")
    return np.array(hashes, dtype=np.uint64), kept


def hamming_matrix(a: np.ndarray, b: np.ndarray, chunk: int = 2048) -> np.ndarray:
    """Min Hamming distance from each element of `a` to any element of `b`.

    Vectorised via bit-unpacking: 1000 x 99,417 pairwise 64-bit popcounts would be slow
    in Python but is a couple of seconds as packed-bit matrix arithmetic.
    """
    a_bits = np.unpackbits(a.view(np.uint8).reshape(-1, 8)[:, ::-1], axis=1).astype(np.int8)
    best = np.full(len(a), 64, dtype=np.int16)
    for start in range(0, len(b), chunk):
        b_chunk = b[start : start + chunk]
        b_bits = np.unpackbits(b_chunk.view(np.uint8).reshape(-1, 8)[:, ::-1], axis=1).astype(np.int8)
        # XOR via (a != b) summed over bits.
        d = (a_bits[:, None, :] != b_bits[None, :, :]).sum(axis=2).astype(np.int16)
        best = np.minimum(best, d.min(axis=1))
    return best


def main() -> None:
    ap = argparse.ArgumentParser(description="Deduplicate pretraining corpus vs Kvasir-SEG")
    ap.add_argument("--pretrain-root", default=None)
    ap.add_argument("--kvasir-root", default=None)
    ap.add_argument("--threshold", type=int, default=6, help="max Hamming distance to call a match")
    ap.add_argument("--out", default=str(REPO_ROOT / "splits" / "pretrain_excluded.txt"))
    ap.add_argument("--report", default=str(REPO_ROOT / "splits" / "dedup_report.json"))
    args = ap.parse_args()

    pre_root = Path(args.pretrain_root) if args.pretrain_root else resolve_dataset_dir("hyperkvasir")
    kv_root = Path(args.kvasir_root) if args.kvasir_root else resolve_dataset_dir("kvasir_seg")
    kv_images, _ = find_image_and_mask_dirs(kv_root)

    pre_paths = sorted(p for p in pre_root.rglob("*") if p.suffix.lower() in IMAGE_EXTS)
    kv_paths = sorted(p for p in kv_images.iterdir() if p.suffix.lower() in IMAGE_EXTS)
    print(f"[dedup] pretraining corpus: {len(pre_paths)} images ({pre_root})")
    print(f"[dedup] Kvasir-SEG:         {len(kv_paths)} images ({kv_images})")

    kv_hashes, _ = hash_dir(kv_paths, "kvasir-seg")
    pre_hashes, pre_kept = hash_dir(pre_paths, "hyperkvasir")

    print("[dedup] computing pairwise distances ...")
    best = hamming_matrix(pre_hashes, kv_hashes)
    matched = [p for p, d in zip(pre_kept, best) if d <= args.threshold]

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "# HyperKvasir images excluded from pretraining because they near-duplicate a\n"
        "# Kvasir-SEG image (perceptual hash, Hamming <= "
        f"{args.threshold}). Generated by scripts/dedup_phash.py.\n"
        + "\n".join(p.name for p in matched)
        + "\n"
    )

    # Distance histogram makes the threshold choice auditable rather than arbitrary.
    hist = {int(d): int((best == d).sum()) for d in range(0, 17)}
    report = {
        "threshold": args.threshold,
        "pretrain_images": len(pre_kept),
        "kvasir_images": len(kv_hashes),
        "excluded": len(matched),
        "excluded_pct": round(100 * len(matched) / max(1, len(pre_kept)), 3),
        "remaining": len(pre_kept) - len(matched),
        "distance_histogram_0_to_16": hist,
    }
    Path(args.report).write_text(json.dumps(report, indent=2) + "\n")

    print(
        f"\n[dedup] {len(matched)} / {len(pre_kept)} pretraining images "
        f"({report['excluded_pct']}%) near-duplicate a Kvasir-SEG image and were excluded."
    )
    print(f"[dedup] {report['remaining']} images remain for pretraining.")
    print(f"[dedup] wrote {out} and {args.report}")
    print("[dedup] Report the excluded count in the thesis — it pre-empts the "
          "pretraining/test contamination objection.")


if __name__ == "__main__":
    main()
